name: Trigger auto deployment for authentication-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '/Services/Authentication/**'
    - '.github/workflows/authentication-app-AutoDeployTrigger-08ed2610-e476-4e2b-bbf3-e15f1f2f8214.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AUTHENTICATIONAPP_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/Services/Authentication 
          registryUrl: apr2023cr.azurecr.io
          registryUsername: ${{ secrets.AUTHENTICATIONAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.AUTHENTICATIONAPP_REGISTRY_PASSWORD }}
          containerAppName: authentication-app
          resourceGroup: April2023Batch
          imageToBuild: apr2023cr.azurecr.io/authentication-microservice:${{ github.sha }}
          dockerfilePath: Dockerfile

     

