name: Trigger auto deployment for interview-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '/Services/Interviews/**'
    - '.github/workflows/interview-app-AutoDeployTrigger-517685da-0827-42d3-a6d2-efa91a0463f3.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.INTERVIEWAPP_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/Services/Interviews 
          registryUrl: apr2023cr.azurecr.io
          registryUsername: ${{ secrets.INTERVIEWAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.INTERVIEWAPP_REGISTRY_PASSWORD }}
          containerAppName: interview-app
          resourceGroup: April2023Batch
          imageToBuild: apr2023cr.azurecr.io/interview-app:${{ github.sha }}
          dockerfilePath: Dockerfile

     

