name: Trigger auto deployment for recruiting-container1

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - 'Dockerfile.Recruiting/**'
    - '.github/workflows/recruiting-container1-AutoDeployTrigger-16bbdb22-b07f-40dd-9434-8feab8c3724c.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.RECRUITINGCONTAINER1_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}Dockerfile.Recruiting 
          registryUrl: apr2023cr.azurecr.io
          registryUsername: ${{ secrets.RECRUITINGCONTAINER1_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.RECRUITINGCONTAINER1_REGISTRY_PASSWORD }}
          containerAppName: recruiting-container1
          resourceGroup: April2023Batch
          imageToBuild: apr2023cr.azurecr.io/recruiting-microservice:${{ github.sha }}
          dockerfilePath: Dockerfile

     

